"""Client classes.

Generated by scripts/generate.py from openapi/swagger.json - do not edit by hand.
"""

from __future__ import annotations

import inspect
from typing import Any

from ._transport import AsyncTransport, SyncTransport
from .interpret import DEFAULT_BASE_URL
from .protocol import AsyncTransportProtocol, SyncTransportProtocol
from .resources import (
    AccountResource,
    AesResource,
    AssetsResource,
    AsyncAccountResource,
    AsyncAesResource,
    AsyncAssetsResource,
    AsyncBattlePassResource,
    AsyncCalendarResource,
    AsyncCosmeticsResource,
    AsyncCrewResource,
    AsyncCustomMatchResource,
    AsyncEventsResource,
    AsyncFNResource,
    AsyncFriendsResource,
    AsyncIdentityResource,
    AsyncMapResource,
    AsyncNewsResource,
    AsyncOAuthResource,
    AsyncParsingResource,
    AsyncPlaylistsResource,
    AsyncPowerRankingsResource,
    AsyncProfileResource,
    AsyncQuestsResource,
    AsyncReplaysResource,
    AsyncShopResource,
    AsyncSpritesResource,
    AsyncStatsResource,
    AsyncTournamentsResource,
    AsyncWeaponsResource,
    BattlePassResource,
    CalendarResource,
    CosmeticsResource,
    CrewResource,
    CustomMatchResource,
    EventsResource,
    FNResource,
    FriendsResource,
    IdentityResource,
    MapResource,
    NewsResource,
    OAuthResource,
    ParsingResource,
    PlaylistsResource,
    PowerRankingsResource,
    ProfileResource,
    QuestsResource,
    ReplaysResource,
    ShopResource,
    SpritesResource,
    StatsResource,
    TournamentsResource,
    WeaponsResource,
)
from .retry import RetryConfig

__all__ = ["DEFAULT_BASE_URL", "AsyncFortniteAPI", "FortniteAPI"]


def _built_in_options(
    transport: object,
    api_key: str | None,
    options: dict[str, object],
) -> dict[str, Any]:
    """Validate the constructor arguments and return the options for a built-in transport."""
    given = sorted(name for name, value in options.items() if value is not None)
    if transport is not None:
        if api_key is not None or given:
            names = ", ".join(["api_key", *given] if api_key is not None else given)
            raise ValueError(f"configure {names} on the transport instead of passing them with transport=")
        return {}
    if not api_key:
        raise ValueError("api_key is required (or pass transport=)")
    return {name: value for name, value in options.items() if value is not None}


def _check_transport(transport: object, *, is_async: bool) -> None:
    """Reject a sync transport given to the async client and vice versa (``isinstance`` cannot tell)."""
    request = getattr(transport, "request", None)
    if not callable(request) or inspect.iscoroutinefunction(request) is not is_async:
        client, expected, kind = (
            ("AsyncFortniteAPI", "AsyncTransportProtocol", "an async def request()")
            if is_async
            else ("FortniteAPI", "SyncTransportProtocol", "a plain def request()")
        )
        raise TypeError(f"{client}(transport=...) needs a {expected} implementation with {kind}")


class FortniteAPI:
    """Client for the Fortnite API (https://api-fortnite.com).

    Pass ``api_key`` (plus optional settings) to use the built-in httpx transport, or
    ``transport=`` any object implementing :class:`~fortnite_api.protocol.SyncTransportProtocol`
    (settings are then configured on that transport and ``api_key`` must be omitted).
    Redirects are not followed unless ``follow_redirects=True``, and retries are disabled
    unless ``retry=`` is given. ``close()`` only closes a transport the client created.
    A transport whose ``request`` is a coroutine function raises ``TypeError``.
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        base_url: str | None = None,
        timeout: float | None = None,
        fortnite_token: str | None = None,
        retry: RetryConfig | None = None,
        follow_redirects: bool | None = None,
        max_redirects: int | None = None,
        user_agent: str | None = None,
        transport: SyncTransportProtocol | None = None,
    ) -> None:
        options = _built_in_options(
            transport,
            api_key,
            {
                "base_url": base_url,
                "timeout": timeout,
                "fortnite_token": fortnite_token,
                "retry": retry,
                "follow_redirects": follow_redirects,
                "max_redirects": max_redirects,
                "user_agent": user_agent,
            },
        )
        self._owned: SyncTransport | None = None
        if transport is not None:
            _check_transport(transport, is_async=False)
        else:
            self._owned = SyncTransport(api_key or "", **options)
            transport = self._owned
        self._t: SyncTransportProtocol = transport
        self.account = AccountResource(self._t)
        self.aes = AesResource(self._t)
        self.assets = AssetsResource(self._t)
        self.battlepass = BattlePassResource(self._t)
        self.calendar = CalendarResource(self._t)
        self.cosmetics = CosmeticsResource(self._t)
        self.crew = CrewResource(self._t)
        self.custom_match = CustomMatchResource(self._t)
        self.events = EventsResource(self._t)
        self.fn = FNResource(self._t)
        self.friends = FriendsResource(self._t)
        self.identity = IdentityResource(self._t)
        self.map = MapResource(self._t)
        self.news = NewsResource(self._t)
        self.oauth = OAuthResource(self._t)
        self.parsing = ParsingResource(self._t)
        self.playlists = PlaylistsResource(self._t)
        self.power_rankings = PowerRankingsResource(self._t)
        self.profile = ProfileResource(self._t)
        self.quests = QuestsResource(self._t)
        self.replays = ReplaysResource(self._t)
        self.shop = ShopResource(self._t)
        self.sprites = SpritesResource(self._t)
        self.stats = StatsResource(self._t)
        self.tournaments = TournamentsResource(self._t)
        self.weapons = WeaponsResource(self._t)

    @property
    def transport(self) -> SyncTransportProtocol:
        """The transport this client sends requests through."""
        return self._t

    def health(self) -> Any:
        """``GET /health`` - service health check."""
        return self._t.request("GET", "/health", None, retryable=True)

    def health_version(self) -> Any:
        """``GET /health/version`` - deployed API version information."""
        return self._t.request("GET", "/health/version", None, retryable=True)

    def close(self) -> None:
        """Close the built-in transport; a transport passed with ``transport=`` is left open."""
        if self._owned is not None:
            self._owned.close()

    def __repr__(self) -> str:
        return f"FortniteAPI(transport={self._t!r})"

    def __enter__(self) -> FortniteAPI:
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class AsyncFortniteAPI:
    """Client for the Fortnite API (https://api-fortnite.com).

    Pass ``api_key`` (plus optional settings) to use the built-in httpx transport, or
    ``transport=`` any object implementing :class:`~fortnite_api.protocol.AsyncTransportProtocol`
    (settings are then configured on that transport and ``api_key`` must be omitted).
    Redirects are not followed unless ``follow_redirects=True``, and retries are disabled
    unless ``retry=`` is given. ``close()`` only closes a transport the client created.
    A transport whose ``request`` is not a coroutine function raises ``TypeError``.
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        base_url: str | None = None,
        timeout: float | None = None,
        fortnite_token: str | None = None,
        retry: RetryConfig | None = None,
        follow_redirects: bool | None = None,
        max_redirects: int | None = None,
        user_agent: str | None = None,
        transport: AsyncTransportProtocol | None = None,
    ) -> None:
        options = _built_in_options(
            transport,
            api_key,
            {
                "base_url": base_url,
                "timeout": timeout,
                "fortnite_token": fortnite_token,
                "retry": retry,
                "follow_redirects": follow_redirects,
                "max_redirects": max_redirects,
                "user_agent": user_agent,
            },
        )
        self._owned: AsyncTransport | None = None
        if transport is not None:
            _check_transport(transport, is_async=True)
        else:
            self._owned = AsyncTransport(api_key or "", **options)
            transport = self._owned
        self._t: AsyncTransportProtocol = transport
        self.account = AsyncAccountResource(self._t)
        self.aes = AsyncAesResource(self._t)
        self.assets = AsyncAssetsResource(self._t)
        self.battlepass = AsyncBattlePassResource(self._t)
        self.calendar = AsyncCalendarResource(self._t)
        self.cosmetics = AsyncCosmeticsResource(self._t)
        self.crew = AsyncCrewResource(self._t)
        self.custom_match = AsyncCustomMatchResource(self._t)
        self.events = AsyncEventsResource(self._t)
        self.fn = AsyncFNResource(self._t)
        self.friends = AsyncFriendsResource(self._t)
        self.identity = AsyncIdentityResource(self._t)
        self.map = AsyncMapResource(self._t)
        self.news = AsyncNewsResource(self._t)
        self.oauth = AsyncOAuthResource(self._t)
        self.parsing = AsyncParsingResource(self._t)
        self.playlists = AsyncPlaylistsResource(self._t)
        self.power_rankings = AsyncPowerRankingsResource(self._t)
        self.profile = AsyncProfileResource(self._t)
        self.quests = AsyncQuestsResource(self._t)
        self.replays = AsyncReplaysResource(self._t)
        self.shop = AsyncShopResource(self._t)
        self.sprites = AsyncSpritesResource(self._t)
        self.stats = AsyncStatsResource(self._t)
        self.tournaments = AsyncTournamentsResource(self._t)
        self.weapons = AsyncWeaponsResource(self._t)

    @property
    def transport(self) -> AsyncTransportProtocol:
        """The transport this client sends requests through."""
        return self._t

    async def health(self) -> Any:
        """``GET /health`` - service health check."""
        return await self._t.request("GET", "/health", None, retryable=True)

    async def health_version(self) -> Any:
        """``GET /health/version`` - deployed API version information."""
        return await self._t.request("GET", "/health/version", None, retryable=True)

    async def close(self) -> None:
        """Close the built-in transport; a transport passed with ``transport=`` is left open."""
        if self._owned is not None:
            await self._owned.close()

    def __repr__(self) -> str:
        return f"AsyncFortniteAPI(transport={self._t!r})"

    async def __aenter__(self) -> AsyncFortniteAPI:
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.close()
