"""Code generator for the Fortnite API SDK.

Reads openapi/swagger.json and a declarative endpoint table, then emits
src/fortnite_api/models.py, resources/*.py and client.py for sync + async.
Run with: uv run python scripts/generate.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "fortnite_api"
SWAGGER: dict[str, Any] = json.loads((ROOT / "openapi" / "swagger.json").read_text(encoding="utf-8"))

Endpoint = dict[str, Any]
QueryParam = tuple[str, bool, str, str]  # (spec name, required, kind, python name)


GENERATED_NOTE = "{what}.\n\nGenerated by scripts/generate.py from openapi/swagger.json - do not edit by hand.\n"


def snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


# --------------------------------------------------------------------------- models

PY_PRIMITIVE = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}


def model_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).split("/")[-1]
    t = schema.get("type")
    if t == "array":
        return f"list[{model_type(schema.get('items', {}))}]"
    if t in PY_PRIMITIVE:
        return PY_PRIMITIVE[t]
    if t == "object":
        ap = schema.get("additionalProperties")
        if isinstance(ap, dict):
            return f"dict[str, {model_type(ap)}]"
        return "dict[str, Any]"
    if "properties" in schema:
        return "dict[str, Any]"
    return "Any"


def gen_models() -> str:
    schemas = SWAGGER["components"]["schemas"]
    lines = [
        f'"""{GENERATED_NOTE.format(what="Pydantic models for the API schemas")}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "",
        "class FNModel(BaseModel):",
        '    model_config = ConfigDict(populate_by_name=True, extra="allow")',
        "",
    ]
    names = list(schemas)
    for name in names:
        schema = schemas[name]
        props = schema.get("properties") or {}
        lines.append("")
        lines.append(f"class {name}(FNModel):")
        if not props:
            lines.append("    pass")
            continue
        for prop, pschema in props.items():
            py = snake(prop)
            ann = f"{model_type(pschema)} | None"
            if py != prop:
                lines.append(f'    {py}: {ann} = Field(default=None, alias="{prop}")')
            else:
                lines.append(f"    {py}: {ann} = None")
    lines.append("")
    lines.append("")
    lines.append("__all__ = [")
    for name in names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    lines.append("for _m in list(__all__):")
    lines.append("    globals()[_m].model_rebuild()")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- resources

SCHEMA_NAMES = set(SWAGGER["components"]["schemas"])
HTTP_VERBS = ("get", "post", "put", "patch", "delete")
OPS: dict[tuple[str, str], dict[str, Any]] = {
    (verb.upper(), full_path): op
    for full_path, methods in SWAGGER["paths"].items()
    for verb, op in methods.items()
    if verb in HTTP_VERBS
}
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
PATH_RE = re.compile(r"\{([^}]+)\}")
SPEC_KIND = {"integer": "int", "boolean": "bool", "number": "float"}


# Characters ruff (RUF001/RUF002) flags as ambiguous in docstrings, mapped to ASCII.
AMBIGUOUS_CHARS = str.maketrans({"\u2212": "-", "\u2010": "-", "\u2011": "-", "\u00a0": " ", "\u2019": "'"})


def full_swagger_path(version: str | None, path: str) -> str:
    if version is None:
        return path
    return f"/api/{version}{path}"


def spec_op(e: Endpoint) -> dict[str, Any] | None:
    """The swagger operation for an endpoint (None for SDK-only extras not present in the spec)."""
    key = (e["http"], full_swagger_path(e["version"], e["path"]))
    op: dict[str, Any] | None = OPS.get(key)
    if op is None and e["in_spec"]:
        raise SystemExit(f"endpoint {e['name']} -> {key} is not in the spec")
    return op


def norm_query(entry: str | tuple[Any, ...]) -> tuple[str, bool | None, str | None, str | None]:
    """Normalise a query override: name | (name, required, kind, py_name)."""
    if isinstance(entry, str):
        entry = (entry,)
    orig = entry[0]
    required = entry[1] if len(entry) > 1 else None
    kind = entry[2] if len(entry) > 2 else None
    py = entry[3] if len(entry) > 3 else None
    return orig, required, kind, py


def resolve_query(e: Endpoint) -> list[QueryParam]:
    """Merge the spec's query parameters with the per-endpoint overrides.

    Every spec query parameter is exposed; overrides only adjust required/kind/py-name.
    """
    op = spec_op(e)
    overrides = {o[0]: o for o in e["query_overrides"]}
    out: list[QueryParam] = []
    spec_params = [p for p in (op or {}).get("parameters", []) if p.get("in") == "query"]
    seen: set[str] = set()
    for param in spec_params:
        name = param["name"]
        seen.add(name)
        _, o_required, o_kind, py = overrides.get(name, (name, None, None, None))
        required = bool(param.get("required", False)) if o_required is None else o_required
        kind = spec_kind(param) if o_kind is None else o_kind
        out.append((name, required, kind, py or snake(name)))
    for name, (orig, required, kind, py) in overrides.items():
        if name in seen:
            continue
        if op is not None:
            raise SystemExit(f"endpoint {e['name']}: query override {name!r} is not in the spec")
        out.append((orig, bool(required), kind or "str", py or snake(orig)))
    return out


def spec_kind(param: dict[str, Any]) -> str:
    """The SDK kind (int/bool/float/str) of a spec parameter."""
    return SPEC_KIND.get(str((param.get("schema") or {}).get("type", "")), "str")


def path_params(e: Endpoint) -> list[tuple[str, str]]:
    op = spec_op(e) or {}
    kinds = {p["name"]: spec_kind(p) for p in op.get("parameters", []) if p.get("in") == "path"}
    return [(name, kinds.get(name, "str")) for name in PATH_RE.findall(e["path"])]


def q_pytype(kind: str) -> str:
    if kind in ("csv", "list"):
        return "list[str]"
    return {"int": "int", "bool": "bool", "float": "float"}.get(kind, "str")


def q_value(kind: str, py: str, required: bool) -> str:
    if kind == "csv":
        if required:
            return f'",".join({py})'
        return f'",".join({py}) if {py} is not None else None'
    return py


def ep(
    name: str,
    http: str,
    path: str,
    version: str | None,
    *,
    query: list[str | tuple[Any, ...]] | None = None,
    body: str | None = None,
    body_optional: bool = False,
    ret: str | None = None,
    kind: str = "json",
    in_spec: bool = True,
    deprecated_hint: str | None = None,
    read_only: bool = False,
    costly: bool = False,
) -> Endpoint:
    if read_only and http == "GET":
        raise SystemExit(f"endpoint {name}: read_only is implied for GET")
    if costly and http != "GET":
        raise SystemExit(f"endpoint {name}: costly only applies to GET (other methods are not retried)")
    return {
        "name": name,
        "http": http,
        "path": path,
        "version": version,
        "query_overrides": [norm_query(q) for q in (query or [])],
        "body": body,
        "body_optional": body_optional,
        "ret": ret,
        "kind": kind,
        "in_spec": in_spec,
        "deprecated_hint": deprecated_hint,
        "read_only": read_only,
        "costly": costly,
    }


def json_schema_of(content: dict[str, Any] | None) -> dict[str, Any] | None:
    if not content:
        return None
    for ct in ("application/json", "text/json", "text/plain"):
        if ct in content:
            schema: dict[str, Any] | None = content[ct].get("schema")
            return schema
    first: dict[str, Any] | None = next(iter(content.values())).get("schema")
    return first


def uses_model(ann: str) -> bool:
    return any(tok in SCHEMA_NAMES for tok in IDENT_RE.findall(ann))


def response_type(e: Endpoint) -> str | None:
    """Runtime type expression used to validate the JSON response (None = raw JSON)."""
    if e["kind"] in ("binary", "redirect"):
        return None
    ret: str | None = e["ret"]
    if ret is not None:
        return f"list[{ret[:-2]}]" if ret.endswith("[]") else ret
    op = spec_op(e) or {}
    schema = json_schema_of(op.get("responses", {}).get("200", {}).get("content"))
    if not schema:
        return None
    ann = model_type(schema)
    return ann if uses_model(ann) else None


def return_ann(e: Endpoint) -> str:
    if e["kind"] == "binary":
        return "bytes"
    if e["kind"] == "redirect":
        return "str | None"
    return response_type(e) or "Any"


def body_ann(e: Endpoint) -> str | None:
    if e["kind"] != "json":
        return None
    if e["body"] is not None:
        return str(e["body"])
    op = spec_op(e) or {}
    rb = op.get("requestBody")
    if not rb:
        return None
    schema = json_schema_of(rb.get("content"))
    if not schema:
        return "Any"
    if "$ref" in schema:
        return f"{model_type(schema)} | dict[str, Any]"
    return model_type(schema)


def is_deprecated(e: Endpoint) -> bool:
    op = spec_op(e) or {}
    return bool(op.get("deprecated"))


def py_path(path: str) -> str:
    """The f-string body of ``path`` with every parameter percent-encoded as one path segment."""
    return PATH_RE.sub(lambda m: "{path_segment(" + snake(m.group(1)) + ")}", path)


def is_retryable(e: Endpoint) -> bool:
    """GETs (unless ``costly``) and read-only POST lookups can be retried safely (no side effects)."""
    if e["http"] == "GET":
        return not e["costly"]
    return bool(e["read_only"])


def build_method(e: Endpoint, is_async: bool, attr: str) -> str:
    query = resolve_query(e)
    required_q = [q for q in query if q[1]]
    optional_q = [q for q in query if not q[1]]
    token = e["kind"] in ("json", "binary", "redirect")
    body = body_ann(e)
    rtype = response_type(e)

    pos = [f"{snake(p)}: {q_pytype(k)}" for p, k in path_params(e)]
    pos += [f"{py}: {q_pytype(kind)}" for _orig, _required, kind, py in required_q]
    kw: list[str] = []
    if body is not None:
        if e["body_optional"]:
            kw.append(f"body: {body} | None = None")
        else:
            pos.append(f"body: {body}")

    kw += [f"{py}: {q_pytype(kind)} | None = None" for _orig, _required, kind, py in optional_q]
    if token:
        kw.append("fortnite_token: str | None = None")

    if e["kind"] == "multipart":
        pos = ["file: FileInput"]
        kw = ["filename: str | None = None"]
    elif e["kind"] == "multipart_multi":
        pos = ["files: list[FileInput]"]
        kw = ["filenames: list[str] | None = None"]

    sig = ["self", *pos]
    if kw:
        sig.append("*")
        sig += kw

    async_kw = "async " if is_async else ""
    await_kw = "await " if is_async else ""
    head = f"    {async_kw}def {e['name']}({', '.join(sig)}) -> {return_ann(e)}:"

    full = full_swagger_path(e["version"], e["path"])
    op = spec_op(e) or {}
    summary = " ".join((op.get("summary") or "").split()) or f"{e['http']} {full}"
    summary = summary.translate(AMBIGUOUS_CHARS).replace("\\", "\\\\").replace('"""', "'''")
    deprecated = is_deprecated(e)
    doc_body = [*textwrap.wrap(summary, 100), "", f"``{e['http']} {full}``"]
    warn_lines: list[str] = []
    if deprecated:
        hint = e["deprecated_hint"]
        doc_body += ["", ".. deprecated::", "    This endpoint is marked as deprecated by the API."]
        if hint:
            doc_body.append(f"    {hint}")
        msg = f"{attr}.{e['name']}() calls {e['http']} {full}, which is deprecated by the API."
        if hint:
            msg += f" {hint}"
        msg_parts = textwrap.wrap(msg, 90, drop_whitespace=False, break_on_hyphens=False)
        warn_lines = [
            "        warnings.warn(",
            "            (",
            *(f"                {part!r}" for part in msg_parts),
            "            ),",
            "            DeprecationWarning,",
            "            stacklevel=2,",
            "        )",
        ]
    doc = ['        """' + doc_body[0]] + [("        " + ln) if ln else "" for ln in doc_body[1:]] + ['        """']

    pp = py_path(e["path"])
    path_expr = f'f"{pp}"' if "{" in pp else f'"{pp}"'
    version_expr = "None" if e["version"] is None else f'"{e["version"]}"'

    if query:
        pairs = ", ".join(f'"{orig}": {q_value(kind, py, required)}' for orig, required, kind, py in query)
        params_expr = "{" + pairs + "}"
    else:
        params_expr = "None"
    rt_expr = rtype or "None"
    retry_arg = ", retryable=True" if is_retryable(e) else ""

    if e["kind"] == "binary":
        call = f"self._t.request_binary({path_expr}, {version_expr}, fortnite_token=fortnite_token)"
        body_lines = [f"        return {await_kw}{call}"]
    elif e["kind"] == "redirect":
        body_lines = [
            f"        return {await_kw}self._t.request_redirect({path_expr}, {version_expr}, "
            f"params={params_expr}, fortnite_token=fortnite_token)"
        ]
    elif e["kind"] == "multipart":
        body_lines = [
            '        payload = {"file": file_tuple(file, filename)}',
            f"        return {await_kw}self._t.request_multipart({path_expr}, payload, response_type={rt_expr})",
        ]
    elif e["kind"] == "multipart_multi":
        body_lines = [
            "        payload = [",
            '            ("files", file_tuple(f, filenames[i] if filenames else None))',
            "            for i, f in enumerate(files)",
            "        ]",
            f"        return {await_kw}self._t.request_multipart({path_expr}, payload, response_type={rt_expr})",
        ]
    else:
        body_expr = "body" if body is not None else "None"
        body_lines = [
            f'        return {await_kw}self._t.request("{e["http"]}", {path_expr}, {version_expr},',
            f"            params={params_expr}, json_body={body_expr}, fortnite_token=fortnite_token,",
            f"            response_type={rt_expr}{retry_arg})",
        ]

    return "\n".join([head, *doc, *warn_lines, *body_lines])


def gen_resource_file(attr: str, prefix: str, endpoints: list[Endpoint]) -> str:
    anns = []
    for e in endpoints:
        anns.append(return_ann(e))
        b = body_ann(e)
        if b:
            anns.append(b)
    models_used = sorted({tok for ann in anns for tok in IDENT_RE.findall(ann) if tok in SCHEMA_NAMES})
    has_multipart = any(e["kind"].startswith("multipart") for e in endpoints)
    uses_any = any("Any" in IDENT_RE.findall(ann) for ann in anns)
    has_deprecated = any(is_deprecated(e) for e in endpoints)

    header = [f'"""{prefix} resource (generated by scripts/generate.py - do not edit by hand)."""', ""]
    header += ["from __future__ import annotations", ""]
    if has_deprecated:
        header.append("import warnings")
    if uses_any:
        header.append("from typing import Any")
    if has_deprecated or uses_any:
        header.append("")
    uses_path = any("{" in e["path"] for e in endpoints)
    interpret_names = [
        *(["FileInput", "file_tuple"] if has_multipart else []),
        *(["path_segment"] if uses_path else []),
    ]
    if interpret_names:
        header.append(f"from ..interpret import {', '.join(interpret_names)}")
    if models_used:
        header.append(f"from ..models import {', '.join(models_used)}")
    header.append("from ..protocol import AsyncTransportProtocol, SyncTransportProtocol")
    header += ["from ._base import Resource", "", ""]

    blocks = []
    for is_async in (False, True):
        cls = f"Async{prefix}Resource" if is_async else f"{prefix}Resource"
        transport = "AsyncTransportProtocol" if is_async else "SyncTransportProtocol"
        methods = "\n\n".join(build_method(e, is_async, attr) for e in endpoints)
        blocks.append(f"class {cls}(Resource[{transport}]):\n{methods}\n")

    return "\n".join(header) + "\n\n".join(blocks)


BASE_MODULE = '''"""Base class shared by the generated resources (generated by scripts/generate.py)."""

from __future__ import annotations

from typing import Generic, TypeVar

from ..protocol import AsyncTransportProtocol, SyncTransportProtocol

TransportT = TypeVar("TransportT", SyncTransportProtocol, AsyncTransportProtocol)


class Resource(Generic[TransportT]):
    """A group of endpoints bound to a sync or async transport (see :mod:`fortnite_api.protocol`).

    Resources only call the protocol methods and :mod:`fortnite_api.interpret` helpers, never
    private attributes of the built-in transports, so any conforming transport works.
    """

    def __init__(self, transport: TransportT) -> None:
        self._t: TransportT = transport
'''


def format_generated(paths: list[Path]) -> None:
    """Apply the project's ruff lint autofixes and formatter so the output is stable and CI-clean."""
    files = [str(p) for p in paths]
    ruff = [sys.executable, "-m", "ruff"]
    subprocess.run([*ruff, "format", "--quiet", *files], check=True, cwd=ROOT)
    # Remaining lint violations (if any) are reported by `ruff check` in CI, not here.
    subprocess.run([*ruff, "check", "--fix-only", "--quiet", *files], check=True, cwd=ROOT, capture_output=True)
    subprocess.run([*ruff, "format", "--quiet", *files], check=True, cwd=ROOT)


# --------------------------------------------------------------------------- endpoint table

# Query parameters are taken from the spec automatically; ``query=`` only overrides
# (name, required, kind, py_name) for individual parameters. Response types are derived
# from the spec's 200 schema unless ``ret=`` is given; request bodies from ``requestBody``.
#
# ``read_only=True`` marks POST operations that only look data up (bulk lookups whose body is
# just the list of IDs to fetch): like every GET they are sent with ``retryable=True`` and may be
# retried by a transport configured with a RetryConfig. POSTs that change state, start flows,
# consume parsing quota (``/parsing*``) or touch OAuth/device credentials stay non-retryable.
#
# ``costly=True`` marks GETs that must not be repeated automatically either: the
# ``/replays/{matchId}/parse*`` endpoints (each call consumes parsing credits) and
# ``/oauth/get-token`` (every call starts a new device-code flow).
RESOURCES: dict[str, tuple[str, list[Endpoint]]] = {
    "account": (
        "Account",
        [
            ep("get_by_id", "GET", "/account/{accountId}", "v1"),
            ep("get_bulk", "GET", "/account/bulk", "v1", query=[("accountId", True, "list", "account_ids")]),
            ep("get_by_display_name", "GET", "/account/displayName/{displayName}", "v1"),
            ep("get_display_names", "GET", "/account/displaynames", "v1", query=[("ids", True, "csv", "account_ids")]),
            ep("bulk_external_display_names", "POST", "/account/external/displayNames/bulk", "v1", read_only=True),
            ep("bulk_external_ids", "POST", "/account/external/ids/bulk", "v1", read_only=True),
            ep(
                "get_by_external_display_name",
                "GET",
                "/account/external/{externalAuthType}/displayName/{displayName}",
                "v1",
                query=[("caseInsensitive", False, "bool")],
            ),
            ep("get_epic_id_sdk", "GET", "/account/sdk", "v1", query=[("accountId", True, "csv", "account_ids")]),
            ep("get_external_auths", "GET", "/account/{accountId}/externalAuths", "v1"),
            ep("get_external_auth", "GET", "/account/{accountId}/externalAuths/{authType}", "v1"),
        ],
    ),
    "aes": (
        "Aes",
        [
            ep("get_keys", "GET", "/aes", "v1"),
            ep("get_history", "GET", "/aes/history", "v1"),
            ep("get_mappings", "GET", "/mappings", "v1"),
        ],
    ),
    "assets": (
        "Assets",
        [
            ep("get_shop_bundles", "GET", "/assets/bundles/shop", "v1"),
            ep("get_tournament_bundles", "GET", "/assets/bundles/tournaments", "v1"),
        ],
    ),
    "battlepass": (
        "BattlePass",
        [
            ep("get", "GET", "/battlepass", "v2"),
            ep("get_seasons", "GET", "/battlepass/seasons", "v2"),
            ep(
                "get_legacy",
                "GET",
                "/shop/battlepass",
                "v1",
                deprecated_hint="Use battlepass.get() (GET /api/v2/battlepass) instead.",
            ),
        ],
    ),
    "calendar": (
        "Calendar",
        [
            ep("get_season", "GET", "/season", "v1"),
        ],
    ),
    "cosmetics": (
        "Cosmetics",
        [
            ep("get_all", "GET", "/cosmetics/all", "v2"),
            ep("get_new", "GET", "/cosmetics/new", "v2"),
            ep("search", "GET", "/cosmetics/search", "v2", query=[("q", True, "str")]),
            ep("get_by_id", "GET", "/cosmetics/{id}", "v2"),
        ],
    ),
    "crew": (
        "Crew",
        [
            ep("get_current", "GET", "/crew/current", "v1"),
            ep("get_history", "GET", "/crew/history", "v1"),
        ],
    ),
    "custom_match": (
        "CustomMatch",
        [
            ep("initiate", "POST", "/custom-match/initiate", "v1"),
            ep("get_status", "GET", "/custom-match/status/{playerId}", "v1"),
            ep("get_bots", "GET", "/custom-match/bots", "v1"),
            ep("register_account", "POST", "/custom-match/accounts", "v1"),
            ep("delete_account", "DELETE", "/custom-match/accounts/{id}", "v1"),
        ],
    ),
    "events": (
        "Events",
        [
            ep("get_player_history", "GET", "/events/players/{accountId}/history", "v2"),
            ep("get_window_leaderboard", "GET", "/events/{eventId}/windows/{eventWindowId}/leaderboard", "v2"),
            ep(
                "get_window_leaderboard_player",
                "GET",
                "/events/{eventId}/windows/{eventWindowId}/leaderboard/player",
                "v2",
            ),
            ep(
                "get_player_window_standing",
                "GET",
                "/events/{eventId}/windows/{eventWindowId}/players/{accountId}",
                "v2",
            ),
        ],
    ),
    "fn": (
        "FN",
        [
            ep("get_br_inventory", "GET", "/fn/br-inventory/{accountId}", "v2"),
            ep("get_enabled_features", "GET", "/fn/enabled-features", "v2"),
            ep("get_entitlement", "GET", "/fn/entitlement", "v2"),
            ep("request_entitlement", "POST", "/fn/entitlement/{accountId}", "v2"),
            ep("get_keychain", "GET", "/fn/keychain", "v2"),
            ep("get_privacy", "GET", "/fn/privacy/{accountId}", "v2"),
            ep("update_privacy", "POST", "/fn/privacy/{accountId}", "v2"),
            ep("get_receipts", "GET", "/fn/receipts/{accountId}", "v2"),
            ep("get_version", "GET", "/fn/version/{platform}", "v2"),
        ],
    ),
    "friends": (
        "Friends",
        [
            ep("get_blocklist", "GET", "/friends/{accountId}/blocklist", "v1"),
            ep("get_friends", "GET", "/friends/{accountId}/friends", "v1"),
            ep("get_friend", "GET", "/friends/{accountId}/friends/{friendId}", "v1"),
            ep("get_mutual_friends", "GET", "/friends/{accountId}/friends/{friendId}/mutual", "v1"),
            ep("get_incoming", "GET", "/friends/{accountId}/incoming", "v1"),
            ep("get_outgoing", "GET", "/friends/{accountId}/outgoing", "v1"),
            ep("get_suggested", "GET", "/friends/{accountId}/suggested", "v1"),
            ep("get_summary", "GET", "/friends/{accountId}/summary", "v1"),
        ],
    ),
    "identity": (
        "Identity",
        [
            ep("link", "POST", "/identity/link", "v1"),
            ep("get", "GET", "/identity/{discordId}", "v1"),
        ],
    ),
    "map": (
        "Map",
        [
            ep("get", "GET", "/map", "v1"),
            ep("get_history", "GET", "/map/history", "v1"),
            ep("get_image", "GET", "/map/image", "v1", kind="redirect"),
        ],
    ),
    "news": (
        "News",
        [
            ep("get_all", "GET", "/news", "v1"),
            ep("get_br", "GET", "/news/br", "v1"),
            ep("get_creative", "GET", "/news/creative", "v1"),
            ep("get_festival", "GET", "/news/festival", "v1"),
            ep("get_notices", "GET", "/news/notices", "v1"),
            ep("get_stw", "GET", "/news/stw", "v1"),
        ],
    ),
    "oauth": (
        "OAuth",
        [
            ep("get_authorize_url", "GET", "/oauth/authorize-url", "v1"),
            ep("complete", "POST", "/oauth/complete", "v1"),
            ep("exchange_code", "POST", "/oauth/exchange-code", "v1"),
            ep("get_token", "GET", "/oauth/get-token", "v1", costly=True),
            ep("link", "POST", "/oauth/link", "v1"),
            ep("refresh_device", "POST", "/oauth/refresh-device", "v1"),
            ep("refresh_token", "POST", "/oauth/refresh-token", "v1"),
            ep("revoke_device", "POST", "/oauth/revoke-device", "v1"),
        ],
    ),
    "parsing": (
        "Parsing",
        [
            ep("parse_replay", "POST", "/parsing", "v1", kind="multipart"),
            ep("parse_stats", "POST", "/parsing/stats", "v1", kind="multipart"),
            ep("parse_map", "POST", "/parsing/map", "v1", kind="multipart"),
            ep("parse_loot", "POST", "/parsing/loot", "v1", kind="multipart"),
            ep("parse_timeline", "POST", "/parsing/timeline", "v1", kind="multipart"),
            ep("parse_zones", "POST", "/parsing/zones", "v1", kind="multipart"),
            ep("parse_lobby", "POST", "/parsing/lobby", "v1", kind="multipart"),
            ep("parse_broadcast", "POST", "/parsing/broadcast", "v1", kind="multipart"),
            # Multi-file parsing endpoints are live but not (yet) published in the OpenAPI spec.
            ep("parse_multiple", "POST", "/parsing/multiple", "v1", kind="multipart_multi", in_spec=False),
            ep("parse_multiple_stats", "POST", "/parsing/multiple/stats", "v1", kind="multipart_multi", in_spec=False),
            ep("parse_multiple_map", "POST", "/parsing/multiple/map", "v1", kind="multipart_multi", in_spec=False),
            ep("parse_multiple_loot", "POST", "/parsing/multiple/loot", "v1", kind="multipart_multi", in_spec=False),
        ],
    ),
    "playlists": (
        "Playlists",
        [
            ep("get_all", "GET", "/playlists", "v2"),
            ep("get_active", "GET", "/playlists/active", "v2"),
            ep("get_by_id", "GET", "/playlists/{playlistId}", "v2"),
        ],
    ),
    "power_rankings": (
        "PowerRankings",
        [
            ep("get_leaderboard", "GET", "/events/powerrankings", "v1"),
            ep("get_player", "GET", "/events/powerrankings/player/{identifier}", "v1"),
            ep("search", "GET", "/events/powerrankings/search", "v1"),
            ep("get_from_archive", "GET", "/events/powerrankings/archive/{accountId}", "v1"),
        ],
    ),
    "profile": (
        "Profile",
        [
            ep("get_leaderboard", "POST", "/profile/leaderboard/{gameId}", "v1", read_only=True),
            ep("get_level", "GET", "/profile/level", "v1"),
            ep("get_progress", "GET", "/profile/progress", "v1"),
            ep("get_ranked", "GET", "/profile/ranked", "v1"),
            ep("bulk_track_progress", "POST", "/profile/trackprogress/bulk", "v1", read_only=True),
            ep("get_tracks", "GET", "/profile/tracks", "v1"),
        ],
    ),
    "quests": (
        "Quests",
        [
            ep("get", "GET", "/quests/{accountId}", "v2"),
            ep("get_definitions", "GET", "/quests/definitions", "v2"),
            ep("get_definition", "GET", "/quests/definitions/{templateId}", "v2"),
        ],
    ),
    "replays": (
        "Replays",
        [
            ep("download", "GET", "/replays/{matchId}", "v1", kind="binary"),
            ep("get_metadata", "GET", "/replays/{matchId}/metadata", "v1"),
            ep("parse", "GET", "/replays/{matchId}/parse", "v1", costly=True),
            ep(
                "parse_broadcast",
                "GET",
                "/replays/{matchId}/parse/broadcast",
                "v1",
                costly=True,
                deprecated_hint="Use replays.parse() or the individual parse_* methods instead.",
            ),
            ep("parse_lobby", "GET", "/replays/{matchId}/parse/lobby", "v1", costly=True),
            ep("parse_loot", "GET", "/replays/{matchId}/parse/loot", "v1", costly=True),
            ep("parse_map", "GET", "/replays/{matchId}/parse/map", "v1", costly=True),
            ep("parse_stats", "GET", "/replays/{matchId}/parse/stats", "v1", costly=True),
            ep("parse_timeline", "GET", "/replays/{matchId}/parse/timeline", "v1", costly=True),
            ep("parse_tracks", "GET", "/replays/{matchId}/parse/tracks", "v1", costly=True),
            ep("parse_zones", "GET", "/replays/{matchId}/parse/zones", "v1", costly=True),
        ],
    ),
    "shop": (
        "Shop",
        [
            ep("get_current", "GET", "/shop", "v1"),
        ],
    ),
    "sprites": (
        "Sprites",
        [
            ep("get", "GET", "/sprites", "v2"),
            ep("get_all", "GET", "/sprites/all", "v2"),
            ep("get_versions", "GET", "/sprites/versions", "v2"),
            ep("get_boons", "GET", "/sprites/boons", "v2"),
            ep("get_by_id", "GET", "/sprites/{id}", "v2"),
            ep("get_collection", "GET", "/sprites/collection", "v2"),
            ep("get_all_collections", "GET", "/sprites/collection/all", "v2"),
            ep("publish_collection", "POST", "/sprites/collection/publish", "v2", body_optional=True),
            ep("unpublish_collection", "DELETE", "/sprites/collection/publish", "v2"),
            ep("get_shared_collection", "GET", "/sprites/collection/shared/{accountIdOrName}", "v2"),
        ],
    ),
    "stats": (
        "Stats",
        [
            ep("get_bulk", "POST", "/stats/bulk", "v2", read_only=True),
            ep("get_leaderboard", "GET", "/stats/leaderboard/{stat}", "v2"),
            ep("get", "GET", "/stats/{accountId}", "v2"),
        ],
    ),
    "tournaments": (
        "Tournaments",
        [
            ep("get_cashprize", "GET", "/events/cashprize/{eventWindowId}", "v1"),
            ep("get_cashprizes", "GET", "/events/cashprizes", "v1"),
            ep("get_current", "GET", "/events/global", "v1"),
            ep("get_global_history", "GET", "/events/global/history", "v1"),
            ep("get_leaderboard", "GET", "/events/global/leaderboard", "v1"),
            ep("get_player", "GET", "/events/player", "v1"),
            ep("get_player_matches", "GET", "/events/player/{accountId}/matches", "v1"),
            ep("get_player_session", "GET", "/events/player/{accountId}/session", "v1"),
            ep(
                "get_player_window_matches", "GET", "/events/{eventId}/{eventWindowId}/player/{accountId}/matches", "v1"
            ),
            ep("get_scoring", "GET", "/events/scoring", "v1"),
            ep("get_window_scoring", "GET", "/events/scoring/{eventWindowId}", "v1"),
            ep("get_sessions", "GET", "/events/sessions", "v1"),
            ep("get_stat_leaders", "GET", "/events/stats/{eventId}/{eventWindowId}/{statKey}", "v1"),
            ep("get_team_stats", "GET", "/events/stats/{eventId}/{eventWindowId}/{statKey}/{teamIdentifier}", "v1"),
            ep(
                "get_tokens", "GET", "/events/tokens", "v1", query=[("teamAccountIds", True, "csv", "team_account_ids")]
            ),
            ep("get_tracker", "GET", "/events/tracker", "v1"),
            ep("get_tracker_eligibility", "GET", "/events/tracker/eligibility", "v1"),
            ep("check_eligibility", "GET", "/events/tracker/eligibility/{identifier}/{eventId}", "v1"),
        ],
    ),
    "weapons": (
        "Weapons",
        [
            ep("get", "GET", "/weapons", "v2"),
            ep("get_by_id", "GET", "/weapons/{id}", "v2"),
            ep("get_lootpool", "GET", "/weapons/lootpool", "v2"),
            ep("get_patches", "GET", "/weapons/patches", "v2"),
            ep("get_rarities", "GET", "/weapons/rarity", "v2"),
        ],
    ),
}


def gen_resources_init() -> str:
    lines = [f'"""{GENERATED_NOTE.format(what="Resource classes")}"""', "", "from __future__ import annotations", ""]
    for attr, (prefix, _) in RESOURCES.items():
        lines.append(f"from .{attr} import {prefix}Resource, Async{prefix}Resource")
    lines.append("")
    lines.append("__all__ = [")
    for prefix, _ in RESOURCES.values():
        lines.append(f'    "{prefix}Resource",')
        lines.append(f'    "Async{prefix}Resource",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


CLIENT_HELPERS = '''
def _built_in_options(
    transport: object,
    api_key: str | None,
    options: dict[str, object],
) -> dict[str, Any]:
    """Validate the constructor arguments and return the options for a built-in transport."""
    given = sorted(name for name, value in options.items() if value is not None)
    if transport is not None:
        if api_key is not None or given:
            names = ", ".join(["api_key", *given] if api_key is not None else given)
            raise ValueError(f"configure {names} on the transport instead of passing them with transport=")
        return {}
    if not api_key:
        raise ValueError("api_key is required (or pass transport=)")
    return {name: value for name, value in options.items() if value is not None}


def _check_transport(transport: object, *, is_async: bool) -> None:
    """Reject a sync transport given to the async client and vice versa (``isinstance`` cannot tell)."""
    request = getattr(transport, "request", None)
    if not callable(request) or inspect.iscoroutinefunction(request) is not is_async:
        client, expected, kind = (
            ("AsyncFortniteAPI", "AsyncTransportProtocol", "an async def request()")
            if is_async
            else ("FortniteAPI", "SyncTransportProtocol", "a plain def request()")
        )
        raise TypeError(f"{client}(transport=...) needs a {expected} implementation with {kind}")
'''


def gen_client() -> str:
    imports = "\n".join(f"    {prefix}Resource,\n    Async{prefix}Resource," for prefix, _ in RESOURCES.values())
    lines = [
        f'"""{GENERATED_NOTE.format(what="Client classes")}"""',
        "",
        "from __future__ import annotations",
        "",
        "import inspect",
        "from typing import Any",
        "",
        "from ._transport import AsyncTransport, SyncTransport",
        "from .interpret import DEFAULT_BASE_URL",
        "from .protocol import AsyncTransportProtocol, SyncTransportProtocol",
        "from .resources import (",
        imports,
        ")",
        "from .retry import RetryConfig",
        "",
        '__all__ = ["DEFAULT_BASE_URL", "AsyncFortniteAPI", "FortniteAPI"]',
        "",
        "",
        CLIENT_HELPERS.strip("\n"),
        "",
        "",
    ]

    def client_class(is_async: bool) -> str:
        cls = "AsyncFortniteAPI" if is_async else "FortniteAPI"
        transport = "AsyncTransport" if is_async else "SyncTransport"
        proto = "AsyncTransportProtocol" if is_async else "SyncTransportProtocol"
        a, aw = ("async ", "await ") if is_async else ("", "")
        body = [
            f"class {cls}:",
            '    """Client for the Fortnite API (https://api-fortnite.com).',
            "",
            "    Pass ``api_key`` (plus optional settings) to use the built-in httpx transport, or",
            f"    ``transport=`` any object implementing :class:`~fortnite_api.protocol.{proto}`",
            "    (settings are then configured on that transport and ``api_key`` must be omitted).",
            "    Redirects are not followed unless ``follow_redirects=True``, and retries are disabled",
            "    unless ``retry=`` is given. ``close()`` only closes a transport the client created.",
            f"    A transport whose ``request`` is {'not ' if is_async else ''}a coroutine function"
            " raises ``TypeError``.",
            '    """',
            "",
            "    def __init__(",
            "        self,",
            "        api_key: str | None = None,",
            "        *,",
            "        base_url: str | None = None,",
            "        timeout: float | None = None,",
            "        fortnite_token: str | None = None,",
            "        retry: RetryConfig | None = None,",
            "        follow_redirects: bool | None = None,",
            "        max_redirects: int | None = None,",
            "        user_agent: str | None = None,",
            f"        transport: {proto} | None = None,",
            "    ) -> None:",
            "        options = _built_in_options(",
            "            transport,",
            "            api_key,",
            "            {",
            '                "base_url": base_url,',
            '                "timeout": timeout,',
            '                "fortnite_token": fortnite_token,',
            '                "retry": retry,',
            '                "follow_redirects": follow_redirects,',
            '                "max_redirects": max_redirects,',
            '                "user_agent": user_agent,',
            "            },",
            "        )",
            f"        self._owned: {transport} | None = None",
            "        if transport is not None:",
            f"            _check_transport(transport, is_async={is_async})",
            "        else:",
            f'            self._owned = {transport}(api_key or "", **options)',
            "            transport = self._owned",
            f"        self._t: {proto} = transport",
        ]
        for attr, (prefix, _) in RESOURCES.items():
            rcls = f"Async{prefix}Resource" if is_async else f"{prefix}Resource"
            body.append(f"        self.{attr} = {rcls}(self._t)")
        body += [
            "",
            "    @property",
            f"    def transport(self) -> {proto}:",
            '        """The transport this client sends requests through."""',
            "        return self._t",
            "",
            f"    {a}def health(self) -> Any:",
            '        """``GET /health`` - service health check."""',
            f'        return {aw}self._t.request("GET", "/health", None, retryable=True)',
            "",
            f"    {a}def health_version(self) -> Any:",
            '        """``GET /health/version`` - deployed API version information."""',
            f'        return {aw}self._t.request("GET", "/health/version", None, retryable=True)',
            "",
            f"    {a}def close(self) -> None:",
            '        """Close the built-in transport; a transport passed with ``transport=`` is left open."""',
            "        if self._owned is not None:",
            f"            {aw}self._owned.close()",
            "",
            "    def __repr__(self) -> str:",
            f'        return f"{cls}(transport={{self._t!r}})"',
            "",
        ]
        if is_async:
            body += [
                "    async def __aenter__(self) -> AsyncFortniteAPI:",
                "        return self",
                "",
                "    async def __aexit__(self, *exc: Any) -> None:",
                "        await self.close()",
            ]
        else:
            body += [
                "    def __enter__(self) -> FortniteAPI:",
                "        return self",
                "",
                "    def __exit__(self, *exc: Any) -> None:",
                "        self.close()",
            ]
        body.append("")
        return "\n".join(body)

    return "\n".join(lines) + client_class(False) + "\n\n" + client_class(True) + "\n"


def main() -> None:
    res_dir = PKG / "resources"
    res_dir.mkdir(exist_ok=True)
    outputs: dict[Path, str] = {
        PKG / "models.py": gen_models(),
        res_dir / "_base.py": BASE_MODULE,
        **{res_dir / f"{attr}.py": gen_resource_file(attr, prefix, eps) for attr, (prefix, eps) in RESOURCES.items()},
        res_dir / "__init__.py": gen_resources_init(),
        PKG / "client.py": gen_client(),
    }
    for path, source in outputs.items():
        path.write_text(source, encoding="utf-8", newline="\n")
    format_generated(sorted(outputs))

    total = sum(len(v[1]) for v in RESOURCES.values())
    print(f"generated {len(SWAGGER['components']['schemas'])} models, {len(RESOURCES)} resources, {total} endpoints")


if __name__ == "__main__":
    main()
