"""Resource classes.

Generated by scripts/generate.py from openapi/swagger.json - do not edit by hand.
"""

from __future__ import annotations

from .account import AccountResource, AsyncAccountResource
from .aes import AesResource, AsyncAesResource
from .assets import AssetsResource, AsyncAssetsResource
from .battlepass import AsyncBattlePassResource, BattlePassResource
from .calendar import AsyncCalendarResource, CalendarResource
from .cosmetics import AsyncCosmeticsResource, CosmeticsResource
from .crew import AsyncCrewResource, CrewResource
from .custom_match import AsyncCustomMatchResource, CustomMatchResource
from .events import AsyncEventsResource, EventsResource
from .fn import AsyncFNResource, FNResource
from .friends import AsyncFriendsResource, FriendsResource
from .identity import AsyncIdentityResource, IdentityResource
from .map import AsyncMapResource, MapResource
from .news import AsyncNewsResource, NewsResource
from .oauth import AsyncOAuthResource, OAuthResource
from .parsing import AsyncParsingResource, ParsingResource
from .playlists import AsyncPlaylistsResource, PlaylistsResource
from .power_rankings import AsyncPowerRankingsResource, PowerRankingsResource
from .profile import AsyncProfileResource, ProfileResource
from .quests import AsyncQuestsResource, QuestsResource
from .replays import AsyncReplaysResource, ReplaysResource
from .shop import AsyncShopResource, ShopResource
from .sprites import AsyncSpritesResource, SpritesResource
from .stats import AsyncStatsResource, StatsResource
from .tournaments import AsyncTournamentsResource, TournamentsResource
from .weapons import AsyncWeaponsResource, WeaponsResource

__all__ = [
    "AccountResource",
    "AesResource",
    "AssetsResource",
    "AsyncAccountResource",
    "AsyncAesResource",
    "AsyncAssetsResource",
    "AsyncBattlePassResource",
    "AsyncCalendarResource",
    "AsyncCosmeticsResource",
    "AsyncCrewResource",
    "AsyncCustomMatchResource",
    "AsyncEventsResource",
    "AsyncFNResource",
    "AsyncFriendsResource",
    "AsyncIdentityResource",
    "AsyncMapResource",
    "AsyncNewsResource",
    "AsyncOAuthResource",
    "AsyncParsingResource",
    "AsyncPlaylistsResource",
    "AsyncPowerRankingsResource",
    "AsyncProfileResource",
    "AsyncQuestsResource",
    "AsyncReplaysResource",
    "AsyncShopResource",
    "AsyncSpritesResource",
    "AsyncStatsResource",
    "AsyncTournamentsResource",
    "AsyncWeaponsResource",
    "BattlePassResource",
    "CalendarResource",
    "CosmeticsResource",
    "CrewResource",
    "CustomMatchResource",
    "EventsResource",
    "FNResource",
    "FriendsResource",
    "IdentityResource",
    "MapResource",
    "NewsResource",
    "OAuthResource",
    "ParsingResource",
    "PlaylistsResource",
    "PowerRankingsResource",
    "ProfileResource",
    "QuestsResource",
    "ReplaysResource",
    "ShopResource",
    "SpritesResource",
    "StatsResource",
    "TournamentsResource",
    "WeaponsResource",
]
