"""Base class shared by the generated resources (generated by scripts/generate.py)."""

from __future__ import annotations

from typing import Generic, TypeVar

from .._transport import AsyncTransport, SyncTransport

TransportT = TypeVar("TransportT", SyncTransport, AsyncTransport)


class Resource(Generic[TransportT]):
    """A group of endpoints bound to a :class:`SyncTransport` or :class:`AsyncTransport`."""

    def __init__(self, transport: TransportT) -> None:
        self._t: TransportT = transport
