"""Calendar resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from ..models import SeasonEntryDto
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class CalendarResource(Resource[SyncTransportProtocol]):
    def get_season(self, *, fortnite_token: str | None = None) -> SeasonEntryDto:
        """Get the current Fortnite season number and start/end dates.

        ``GET /api/v1/season``
        """
        return self._t.request(
            "GET",
            "/season",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=SeasonEntryDto,
            retryable=True,
        )


class AsyncCalendarResource(Resource[AsyncTransportProtocol]):
    async def get_season(self, *, fortnite_token: str | None = None) -> SeasonEntryDto:
        """Get the current Fortnite season number and start/end dates.

        ``GET /api/v1/season``
        """
        return await self._t.request(
            "GET",
            "/season",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=SeasonEntryDto,
            retryable=True,
        )
