"""Crew resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from typing import Any

from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class CrewResource(Resource[SyncTransportProtocol]):
    def get_current(self, *, fortnite_token: str | None = None) -> Any:
        """Get the current Fortnite Crew pack.

        ``GET /api/v1/crew/current``
        """
        return self._t.request(
            "GET",
            "/crew/current",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_history(self, *, fortnite_token: str | None = None) -> Any:
        """Get the history of past Fortnite Crew packs.

        ``GET /api/v1/crew/history``
        """
        return self._t.request(
            "GET",
            "/crew/history",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )


class AsyncCrewResource(Resource[AsyncTransportProtocol]):
    async def get_current(self, *, fortnite_token: str | None = None) -> Any:
        """Get the current Fortnite Crew pack.

        ``GET /api/v1/crew/current``
        """
        return await self._t.request(
            "GET",
            "/crew/current",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_history(self, *, fortnite_token: str | None = None) -> Any:
        """Get the history of past Fortnite Crew packs.

        ``GET /api/v1/crew/history``
        """
        return await self._t.request(
            "GET",
            "/crew/history",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )
