"""Friends resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from typing import Any

from ..interpret import path_segment
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class FriendsResource(Resource[SyncTransportProtocol]):
    def get_blocklist(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a player's blocklist.

        ``GET /api/v1/friends/{accountId}/blocklist``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/blocklist",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_friends(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a player's full friends list.

        ``GET /api/v1/friends/{accountId}/friends``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_friend(self, account_id: str, friend_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get details for a specific friend of a player.

        ``GET /api/v1/friends/{accountId}/friends/{friendId}``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends/{path_segment(friend_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_mutual_friends(self, account_id: str, friend_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get mutual friends between two players.

        ``GET /api/v1/friends/{accountId}/friends/{friendId}/mutual``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends/{path_segment(friend_id)}/mutual",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_incoming(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get incoming friend requests for a player.

        ``GET /api/v1/friends/{accountId}/incoming``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/incoming",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_outgoing(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get outgoing friend requests sent by a player.

        ``GET /api/v1/friends/{accountId}/outgoing``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/outgoing",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_suggested(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get suggested friends for a player.

        ``GET /api/v1/friends/{accountId}/suggested``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/suggested",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_summary(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a summary of a player's friends, incoming/outgoing requests, and blocklist counts.

        ``GET /api/v1/friends/{accountId}/summary``
        """
        return self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/summary",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )


class AsyncFriendsResource(Resource[AsyncTransportProtocol]):
    async def get_blocklist(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a player's blocklist.

        ``GET /api/v1/friends/{accountId}/blocklist``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/blocklist",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_friends(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a player's full friends list.

        ``GET /api/v1/friends/{accountId}/friends``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_friend(self, account_id: str, friend_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get details for a specific friend of a player.

        ``GET /api/v1/friends/{accountId}/friends/{friendId}``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends/{path_segment(friend_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_mutual_friends(self, account_id: str, friend_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get mutual friends between two players.

        ``GET /api/v1/friends/{accountId}/friends/{friendId}/mutual``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/friends/{path_segment(friend_id)}/mutual",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_incoming(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get incoming friend requests for a player.

        ``GET /api/v1/friends/{accountId}/incoming``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/incoming",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_outgoing(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get outgoing friend requests sent by a player.

        ``GET /api/v1/friends/{accountId}/outgoing``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/outgoing",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_suggested(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get suggested friends for a player.

        ``GET /api/v1/friends/{accountId}/suggested``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/suggested",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_summary(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get a summary of a player's friends, incoming/outgoing requests, and blocklist counts.

        ``GET /api/v1/friends/{accountId}/summary``
        """
        return await self._t.request(
            "GET",
            f"/friends/{path_segment(account_id)}/summary",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )
