"""Map resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from ..models import MapDataDto, MapHistoryEntryDto
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class MapResource(Resource[SyncTransportProtocol]):
    def get(
        self,
        *,
        version: str | None = None,
        mode: str | None = None,
        lang: str | None = None,
        fortnite_token: str | None = None,
    ) -> MapDataDto:
        """Get map data including POIs and minimap metadata for a given version.

        ``GET /api/v1/map``
        """
        return self._t.request(
            "GET",
            "/map",
            "v1",
            params={"version": version, "mode": mode, "lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=MapDataDto,
            retryable=True,
        )

    def get_history(
        self, *, chapter: int | None = None, season: int | None = None, fortnite_token: str | None = None
    ) -> list[MapHistoryEntryDto]:
        """Get map history entries, optionally filtered by chapter and/or season.

        ``GET /api/v1/map/history``
        """
        return self._t.request(
            "GET",
            "/map/history",
            "v1",
            params={"chapter": chapter, "season": season},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[MapHistoryEntryDto],
            retryable=True,
        )

    def get_image(
        self, *, version: str | None = None, mode: str | None = None, fortnite_token: str | None = None
    ) -> str | None:
        """Redirects to the raw map image on GitHub for a given version.

        ``GET /api/v1/map/image``
        """
        return self._t.request_redirect(
            "/map/image", "v1", params={"version": version, "mode": mode}, fortnite_token=fortnite_token
        )


class AsyncMapResource(Resource[AsyncTransportProtocol]):
    async def get(
        self,
        *,
        version: str | None = None,
        mode: str | None = None,
        lang: str | None = None,
        fortnite_token: str | None = None,
    ) -> MapDataDto:
        """Get map data including POIs and minimap metadata for a given version.

        ``GET /api/v1/map``
        """
        return await self._t.request(
            "GET",
            "/map",
            "v1",
            params={"version": version, "mode": mode, "lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=MapDataDto,
            retryable=True,
        )

    async def get_history(
        self, *, chapter: int | None = None, season: int | None = None, fortnite_token: str | None = None
    ) -> list[MapHistoryEntryDto]:
        """Get map history entries, optionally filtered by chapter and/or season.

        ``GET /api/v1/map/history``
        """
        return await self._t.request(
            "GET",
            "/map/history",
            "v1",
            params={"chapter": chapter, "season": season},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[MapHistoryEntryDto],
            retryable=True,
        )

    async def get_image(
        self, *, version: str | None = None, mode: str | None = None, fortnite_token: str | None = None
    ) -> str | None:
        """Redirects to the raw map image on GitHub for a given version.

        ``GET /api/v1/map/image``
        """
        return await self._t.request_redirect(
            "/map/image", "v1", params={"version": version, "mode": mode}, fortnite_token=fortnite_token
        )
