"""OAuth resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from typing import Any

from ..models import (
    CompleteOAuthRequest,
    ExchangeCodeRequest,
    LinkAccountRequest,
    RefreshDeviceRequest,
    RefreshTokenRequest,
)
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class OAuthResource(Resource[SyncTransportProtocol]):
    def get_authorize_url(self, *, redirect_uri: str | None = None, fortnite_token: str | None = None) -> Any:
        """Returns the Epic Games authorization URL to redirect the user to. The user will see Epic's standard
        login page — no scary device confirmation page. After login, Epic redirects to your redirect_uri
        with ?code=... Then call POST /oauth/link with that code to get the Fortnite access token + device
        auth.

        ``GET /api/v1/oauth/authorize-url``
        """
        return self._t.request(
            "GET",
            "/oauth/authorize-url",
            "v1",
            params={"redirectUri": redirect_uri},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def complete(self, body: CompleteOAuthRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Complete the device code OAuth flow by polling with the flowId returned from GET /oauth/get-token.
        Returns 202 with AUTHORIZATION_PENDING while the user has not yet authenticated. Returns 429 with
        RATE_LIMITED if polling too fast.

        ``POST /api/v1/oauth/complete``
        """
        return self._t.request(
            "POST",
            "/oauth/complete",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def exchange_code(self, body: ExchangeCodeRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Exchange an authorization code for an Epic access token.

        ``POST /api/v1/oauth/exchange-code``
        """
        return self._t.request(
            "POST",
            "/oauth/exchange-code",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def get_token(self, *, fortnite_token: str | None = None) -> Any:
        """Initiate the device code OAuth flow. Returns a flowId and a user-facing URL where the user must
        authenticate. Poll POST /oauth/complete with the flowId to retrieve the token once the user has
        authorized.

        ``GET /api/v1/oauth/get-token``
        """
        return self._t.request(
            "GET",
            "/oauth/get-token",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def link(self, body: LinkAccountRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Exchanges an Epic authorization code for a Fortnite access token and device auth credentials. Use
        the code returned by Epic after the user authorizes via the URL from GET /oauth/authorize-url. The
        returned deviceAuth (accountId + deviceId + secret) can be stored and used with POST /oauth/refresh-
        device to silently re-authenticate in the future — no browser required.

        ``POST /api/v1/oauth/link``
        """
        return self._t.request(
            "POST", "/oauth/link", "v1", params=None, json_body=body, fortnite_token=fortnite_token, response_type=None
        )

    def refresh_device(self, body: RefreshDeviceRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Re-authenticate silently using stored device auth credentials (accountId + deviceId + secret).

        ``POST /api/v1/oauth/refresh-device``
        """
        return self._t.request(
            "POST",
            "/oauth/refresh-device",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def refresh_token(self, body: RefreshTokenRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Refresh an Epic access token using a refresh token.

        ``POST /api/v1/oauth/refresh-token``
        """
        return self._t.request(
            "POST",
            "/oauth/refresh-token",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def revoke_device(self, body: RefreshDeviceRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Revoke a device auth at Epic so it can never be used to log in again. Send the same accountId +
        deviceId + secret that POST /oauth/complete returned; the credential is used once to prove
        ownership, then deleted on Epic's side. We keep no copy of device auths at any point, so this is the
        complete cleanup. 400 when the device auth is already revoked or does not match (Epic rejects the
        login).

        ``POST /api/v1/oauth/revoke-device``
        """
        return self._t.request(
            "POST",
            "/oauth/revoke-device",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )


class AsyncOAuthResource(Resource[AsyncTransportProtocol]):
    async def get_authorize_url(self, *, redirect_uri: str | None = None, fortnite_token: str | None = None) -> Any:
        """Returns the Epic Games authorization URL to redirect the user to. The user will see Epic's standard
        login page — no scary device confirmation page. After login, Epic redirects to your redirect_uri
        with ?code=... Then call POST /oauth/link with that code to get the Fortnite access token + device
        auth.

        ``GET /api/v1/oauth/authorize-url``
        """
        return await self._t.request(
            "GET",
            "/oauth/authorize-url",
            "v1",
            params={"redirectUri": redirect_uri},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def complete(self, body: CompleteOAuthRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Complete the device code OAuth flow by polling with the flowId returned from GET /oauth/get-token.
        Returns 202 with AUTHORIZATION_PENDING while the user has not yet authenticated. Returns 429 with
        RATE_LIMITED if polling too fast.

        ``POST /api/v1/oauth/complete``
        """
        return await self._t.request(
            "POST",
            "/oauth/complete",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def exchange_code(
        self, body: ExchangeCodeRequest | dict[str, Any], *, fortnite_token: str | None = None
    ) -> Any:
        """Exchange an authorization code for an Epic access token.

        ``POST /api/v1/oauth/exchange-code``
        """
        return await self._t.request(
            "POST",
            "/oauth/exchange-code",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def get_token(self, *, fortnite_token: str | None = None) -> Any:
        """Initiate the device code OAuth flow. Returns a flowId and a user-facing URL where the user must
        authenticate. Poll POST /oauth/complete with the flowId to retrieve the token once the user has
        authorized.

        ``GET /api/v1/oauth/get-token``
        """
        return await self._t.request(
            "GET",
            "/oauth/get-token",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def link(self, body: LinkAccountRequest | dict[str, Any], *, fortnite_token: str | None = None) -> Any:
        """Exchanges an Epic authorization code for a Fortnite access token and device auth credentials. Use
        the code returned by Epic after the user authorizes via the URL from GET /oauth/authorize-url. The
        returned deviceAuth (accountId + deviceId + secret) can be stored and used with POST /oauth/refresh-
        device to silently re-authenticate in the future — no browser required.

        ``POST /api/v1/oauth/link``
        """
        return await self._t.request(
            "POST", "/oauth/link", "v1", params=None, json_body=body, fortnite_token=fortnite_token, response_type=None
        )

    async def refresh_device(
        self, body: RefreshDeviceRequest | dict[str, Any], *, fortnite_token: str | None = None
    ) -> Any:
        """Re-authenticate silently using stored device auth credentials (accountId + deviceId + secret).

        ``POST /api/v1/oauth/refresh-device``
        """
        return await self._t.request(
            "POST",
            "/oauth/refresh-device",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def refresh_token(
        self, body: RefreshTokenRequest | dict[str, Any], *, fortnite_token: str | None = None
    ) -> Any:
        """Refresh an Epic access token using a refresh token.

        ``POST /api/v1/oauth/refresh-token``
        """
        return await self._t.request(
            "POST",
            "/oauth/refresh-token",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def revoke_device(
        self, body: RefreshDeviceRequest | dict[str, Any], *, fortnite_token: str | None = None
    ) -> Any:
        """Revoke a device auth at Epic so it can never be used to log in again. Send the same accountId +
        deviceId + secret that POST /oauth/complete returned; the credential is used once to prove
        ownership, then deleted on Epic's side. We keep no copy of device auths at any point, so this is the
        complete cleanup. 400 when the device auth is already revoked or does not match (Epic rejects the
        login).

        ``POST /api/v1/oauth/revoke-device``
        """
        return await self._t.request(
            "POST",
            "/oauth/revoke-device",
            "v1",
            params=None,
            json_body=body,
            fortnite_token=fortnite_token,
            response_type=None,
        )
