"""PowerRankings resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from typing import Any

from .._transport import AsyncTransport, SyncTransport
from ..models import PowerRankingArchiveDto, PowerRankingSearchDto, PowerRankingsPageDto
from ._base import Resource


class PowerRankingsResource(Resource[SyncTransport]):
    def get_leaderboard(
        self, *, page: int | None = None, account_id: str | None = None, fortnite_token: str | None = None
    ) -> PowerRankingsPageDto:
        """Get the Fortnite Power Rankings leaderboard — the official competitive skill rating. Returns 100
        players per page (100 pages total = top 10,000 players). The service account used to query Epic is
        stripped from the response. Supply x-fortnite-token + accountId to also receive the caller's own PR
        entry as `playerEntry` in the response (null if they are unranked). Without a token the response is
        the plain global page — that part needs no auth. trackedStats keys: PR (score), countingEvents (max
        20), peakPerf, deltaPR, peakPR. For a single player use `powerrankings/search` or
        `powerrankings/archive/{accountId}` (no token), or `powerrankings/player/{identifier}` (x-fortnite-
        token required).

        ``GET /api/v1/events/powerrankings``
        """
        return self._t.request(
            "GET",
            "/events/powerrankings",
            "v1",
            params={"page": page, "accountId": account_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingsPageDto,
        )

    def get_player(self, identifier: str, *, fortnite_token: str | None = None) -> Any:
        """Look up a player's Power Rankings entry by display name or account ID. **Requires the x-fortnite-
        token of the player being looked up.**

        ``GET /api/v1/events/powerrankings/player/{identifier}``
        """
        return self._t.request(
            "GET",
            f"/events/powerrankings/player/{identifier}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    def search(
        self, *, q: str | None = None, limit: int | None = None, fortnite_token: str | None = None
    ) -> PowerRankingSearchDto:
        """Search Power Rankings players by display name (partial, case-insensitive). Results come from an in-
        memory index built from the full 10,000-player leaderboard. The index is rebuilt every 2 hours and
        cached in Redis — no user token required.

        ``GET /api/v1/events/powerrankings/search``
        """
        return self._t.request(
            "GET",
            "/events/powerrankings/search",
            "v1",
            params={"q": q, "limit": limit},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingSearchDto,
        )

    def get_from_archive(self, account_id: str, *, fortnite_token: str | None = None) -> PowerRankingArchiveDto:
        """Look up a player's most recent Power Rankings entry by account ID from the archive. Returns rank,
        score, bestRank, peakPr, deltaPr, countingEvents and the last-updated time. Unlike
        `powerrankings/player/{identifier}`, this does NOT require an x-fortnite-token and works for any
        account that has appeared in the top-10,000 leaderboard.

        ``GET /api/v1/events/powerrankings/archive/{accountId}``
        """
        return self._t.request(
            "GET",
            f"/events/powerrankings/archive/{account_id}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingArchiveDto,
        )


class AsyncPowerRankingsResource(Resource[AsyncTransport]):
    async def get_leaderboard(
        self, *, page: int | None = None, account_id: str | None = None, fortnite_token: str | None = None
    ) -> PowerRankingsPageDto:
        """Get the Fortnite Power Rankings leaderboard — the official competitive skill rating. Returns 100
        players per page (100 pages total = top 10,000 players). The service account used to query Epic is
        stripped from the response. Supply x-fortnite-token + accountId to also receive the caller's own PR
        entry as `playerEntry` in the response (null if they are unranked). Without a token the response is
        the plain global page — that part needs no auth. trackedStats keys: PR (score), countingEvents (max
        20), peakPerf, deltaPR, peakPR. For a single player use `powerrankings/search` or
        `powerrankings/archive/{accountId}` (no token), or `powerrankings/player/{identifier}` (x-fortnite-
        token required).

        ``GET /api/v1/events/powerrankings``
        """
        return await self._t.request(
            "GET",
            "/events/powerrankings",
            "v1",
            params={"page": page, "accountId": account_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingsPageDto,
        )

    async def get_player(self, identifier: str, *, fortnite_token: str | None = None) -> Any:
        """Look up a player's Power Rankings entry by display name or account ID. **Requires the x-fortnite-
        token of the player being looked up.**

        ``GET /api/v1/events/powerrankings/player/{identifier}``
        """
        return await self._t.request(
            "GET",
            f"/events/powerrankings/player/{identifier}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
        )

    async def search(
        self, *, q: str | None = None, limit: int | None = None, fortnite_token: str | None = None
    ) -> PowerRankingSearchDto:
        """Search Power Rankings players by display name (partial, case-insensitive). Results come from an in-
        memory index built from the full 10,000-player leaderboard. The index is rebuilt every 2 hours and
        cached in Redis — no user token required.

        ``GET /api/v1/events/powerrankings/search``
        """
        return await self._t.request(
            "GET",
            "/events/powerrankings/search",
            "v1",
            params={"q": q, "limit": limit},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingSearchDto,
        )

    async def get_from_archive(self, account_id: str, *, fortnite_token: str | None = None) -> PowerRankingArchiveDto:
        """Look up a player's most recent Power Rankings entry by account ID from the archive. Returns rank,
        score, bestRank, peakPr, deltaPr, countingEvents and the last-updated time. Unlike
        `powerrankings/player/{identifier}`, this does NOT require an x-fortnite-token and works for any
        account that has appeared in the top-10,000 leaderboard.

        ``GET /api/v1/events/powerrankings/archive/{accountId}``
        """
        return await self._t.request(
            "GET",
            f"/events/powerrankings/archive/{account_id}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PowerRankingArchiveDto,
        )
