"""Shop resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from ..models import ShopResponseDto
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class ShopResource(Resource[SyncTransportProtocol]):
    def get_current(
        self,
        *,
        type: str | None = None,
        section: str | None = None,
        rarity: str | None = None,
        search: str | None = None,
        lang: str | None = None,
        fortnite_token: str | None = None,
    ) -> ShopResponseDto:
        """Get the current Item Shop.

        ``GET /api/v1/shop``
        """
        return self._t.request(
            "GET",
            "/shop",
            "v1",
            params={"type": type, "section": section, "rarity": rarity, "search": search, "lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=ShopResponseDto,
            retryable=True,
        )


class AsyncShopResource(Resource[AsyncTransportProtocol]):
    async def get_current(
        self,
        *,
        type: str | None = None,
        section: str | None = None,
        rarity: str | None = None,
        search: str | None = None,
        lang: str | None = None,
        fortnite_token: str | None = None,
    ) -> ShopResponseDto:
        """Get the current Item Shop.

        ``GET /api/v1/shop``
        """
        return await self._t.request(
            "GET",
            "/shop",
            "v1",
            params={"type": type, "section": section, "rarity": rarity, "search": search, "lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=ShopResponseDto,
            retryable=True,
        )
