"""Tournaments resource (generated by scripts/generate.py - do not edit by hand)."""

from __future__ import annotations

from typing import Any

from ..interpret import path_segment
from ..models import (
    CashPrizeScoringDto,
    EventLeaderboardDto,
    EventSessionDto,
    EventStatsLeaderboardDto,
    EventTokenEligibilityDto,
    GlobalEventDto,
    PlayerTokensDto,
    PlayerWindowStandingDto,
    TeamEventStatsDto,
)
from ..protocol import AsyncTransportProtocol, SyncTransportProtocol
from ._base import Resource


class TournamentsResource(Resource[SyncTransportProtocol]):
    def get_cashprize(self, event_window_id: str, *, fortnite_token: str | None = None) -> list[CashPrizeScoringDto]:
        """Get the payout table for a specific event window.

        ``GET /api/v1/events/cashprize/{eventWindowId}``
        """
        return self._t.request(
            "GET",
            f"/events/cashprize/{path_segment(event_window_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[CashPrizeScoringDto],
            retryable=True,
        )

    def get_cashprizes(self, *, fortnite_token: str | None = None) -> dict[str, list[CashPrizeScoringDto]]:
        """Get all payout tables extracted from Epic's events download. Player data is stripped — only
        reward/prize structures are returned. Response is cached for 4 hours.

        ``GET /api/v1/events/cashprizes``
        """
        return self._t.request(
            "GET",
            "/events/cashprizes",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=dict[str, list[CashPrizeScoringDto]],
            retryable=True,
        )

    def get_current(self, *, lang: str | None = None, fortnite_token: str | None = None) -> list[GlobalEventDto]:
        """Get currently active and upcoming tournaments, enriched with CMS metadata.

        ``GET /api/v1/events/global``
        """
        return self._t.request(
            "GET",
            "/events/global",
            "v1",
            params={"lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[GlobalEventDto],
            retryable=True,
        )

    def get_global_history(self, *, lang: str | None = None, fortnite_token: str | None = None) -> list[GlobalEventDto]:
        """Get all tournaments including past ones, enriched with CMS metadata.

        ``GET /api/v1/events/global/history``
        """
        return self._t.request(
            "GET",
            "/events/global/history",
            "v1",
            params={"lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[GlobalEventDto],
            retryable=True,
        )

    def get_leaderboard(
        self,
        *,
        event_id: str | None = None,
        event_window_id: str | None = None,
        page: int | None = None,
        leaderboard_def: str | None = None,
        account_id: str | None = None,
        cumulative_id: str | None = None,
        fortnite_token: str | None = None,
    ) -> EventLeaderboardDto:
        """Get a paginated tournament leaderboard for the given event window.

        ``GET /api/v1/events/global/leaderboard``
        """
        return self._t.request(
            "GET",
            "/events/global/leaderboard",
            "v1",
            params={
                "eventId": event_id,
                "eventWindowId": event_window_id,
                "page": page,
                "leaderboardDef": leaderboard_def,
                "accountId": account_id,
                "cumulativeId": cumulative_id,
            },
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventLeaderboardDto,
            retryable=True,
        )

    def get_player(
        self,
        *,
        region: str | None = None,
        platform: str | None = None,
        account_id: str | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Get the authenticated player's tournament data — token progression and event participation. Requires
        x-fortnite-token and accountId.

        ``GET /api/v1/events/player``
        """
        return self._t.request(
            "GET",
            "/events/player",
            "v1",
            params={"region": region, "platform": platform, "accountId": account_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_player_matches(
        self,
        account_id: str,
        *,
        after: str | None = None,
        before: str | None = None,
        region: str | None = None,
        platform: str | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Get a player's RECENT tournament sessions (session IDs), grouped by event window. Sourced from
        Epic's player-scoped /download data, which Epic keeps for roughly the last 36 hours only (measured
        2026-09-01) — this is not a full history. Tournament sessions only: private custom-key matches are
        not events and never appear here. Epic only serves this data to the player it belongs to, so
        x-fortnite-token is required for any account other than the service account (403 otherwise). For a
        180-day participation history use GET /events/tracker; for a token-less lookup of one tournament use
        GET {eventId}/{eventWindowId}/player/{accountId}/matches; for the match a player is in right now use
        GET player/{accountId}/session.

        ``GET /api/v1/events/player/{accountId}/matches``
        """
        return self._t.request(
            "GET",
            f"/events/player/{path_segment(account_id)}/matches",
            "v1",
            params={"after": after, "before": before, "region": region, "platform": platform},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_player_session(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get the match a consenting player is in right now — any mode: Battle Royale, Reload, Ranked, or a
        custom-key scrim hosted by anyone. Requires the player's OWN x-fortnite-token: the token is verified
        against the accountId before anything is forwarded (403 otherwise). That token comes from Epic's
        device-authorization flow, which authenticates as the Fortnite client rather than as your
        application; Epic Account Services developer terms do not allow routing your users through it, so it
        suits tools a player runs for themselves, not third-party apps asking other players to log in.
        Because Fortnite kills every other session of an account when the game launches, store the
        deviceAuth that POST /oauth/complete returns and re-authenticate with POST /oauth/refresh-device on
        401. When Epic publishes it, sessionId is the replay match ID — pass it to /replays/{matchId} once
        the match has ended; playlist lets you filter (e.g. scrims) before parsing, and playlistSource says
        whether that playlist is the match being played (currentIsland) or only the lobby selection
        (islandSelection). sessionId can be null while inMatch is true: the id lives in the party fields the
        client uses to advertise "my friends may join or watch me", and a match that cannot be joined or
        watched can publish them empty for its whole duration. sessionSource names the field the id came
        from, and diagnostics reports, per field, whether Epic sent it present, empty or absent — presence
        only, never a value. When every field is empty, note says so and polling harder does not change it.
        The custom match key is never returned (hasCustomKey only); teammates are listed by account id only.
        inParty is false when the player's client is offline. Cached 10 s per account — polling faster gains
        nothing — and Epic's own party state lags the real match by 1-2 min. Rate limit: 1200 requests/min
        per API key.

        ``GET /api/v1/events/player/{accountId}/session``
        """
        return self._t.request(
            "GET",
            f"/events/player/{path_segment(account_id)}/session",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_player_window_matches(
        self,
        event_id: str,
        event_window_id: str,
        account_id: str,
        *,
        rank_hint: int | None = None,
        max_pages: int | None = None,
        fortnite_token: str | None = None,
    ) -> PlayerWindowStandingDto:
        """Get a player's matches (session IDs + per-match stats) in one event window, without any player
        token: the leaderboard is scanned page by page until the player's team is found. Pass rankHint
        (their approximate final rank) to hit the right page first — without it up to maxPages pages are
        scanned in order.

        ``GET /api/v1/events/{eventId}/{eventWindowId}/player/{accountId}/matches``
        """
        return self._t.request(
            "GET",
            f"/events/{path_segment(event_id)}/{path_segment(event_window_id)}/player/{path_segment(account_id)}/matches",
            "v1",
            params={"rankHint": rank_hint, "maxPages": max_pages},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PlayerWindowStandingDto,
            retryable=True,
        )

    def get_scoring(self, *, fortnite_token: str | None = None) -> Any:
        """Get the per-match scoring rules (placement/elimination reward tiers) for every event window, keyed
        by eventWindowId. Extracted from Epic's events data (scoringRuleSets + scoreLocationScoringRuleSets,
        with event-template fallback).

        ``GET /api/v1/events/scoring``
        """
        return self._t.request(
            "GET",
            "/events/scoring",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_window_scoring(self, event_window_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get the per-match scoring rules for a specific event window — the authoritative "how does this
        session score" (exists before the first game is played, and differs between a weekly cup's qualifier
        round and its final).

        ``GET /api/v1/events/scoring/{eventWindowId}``
        """
        return self._t.request(
            "GET",
            f"/events/scoring/{path_segment(event_window_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_sessions(self, *, event_id: str | None = None, fortnite_token: str | None = None) -> EventSessionDto:
        """Get sessions for a specific event.

        ``GET /api/v1/events/sessions``
        """
        return self._t.request(
            "GET",
            "/events/sessions",
            "v1",
            params={"eventId": event_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventSessionDto,
            retryable=True,
        )

    def get_stat_leaders(
        self,
        event_id: str,
        event_window_id: str,
        stat_key: str,
        *,
        top: int | None = None,
        fortnite_token: str | None = None,
    ) -> EventStatsLeaderboardDto:
        """Get the top performers for a specific tracked stat across the entire leaderboard. Fetches all pages
        in parallel batches so low-scoring but high-stat teams (e.g. top fraggers in a placement-only event)
        are always included regardless of their leaderboard position. Response includes an `availableStats`
        array listing every stat key tracked in this tournament.

        ``GET /api/v1/events/stats/{eventId}/{eventWindowId}/{statKey}``
        """
        return self._t.request(
            "GET",
            f"/events/stats/{path_segment(event_id)}/{path_segment(event_window_id)}/{path_segment(stat_key)}",
            "v1",
            params={"top": top},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventStatsLeaderboardDto,
            retryable=True,
        )

    def get_team_stats(
        self,
        event_id: str,
        event_window_id: str,
        stat_key: str,
        team_identifier: str,
        *,
        twitter: bool | None = None,
        fortnite_token: str | None = None,
    ) -> TeamEventStatsDto:
        """Get all tracked stats for a specific team identified by Epic account ID or display name. Returns
        every stat tracked in this tournament for that team (total + per-game), plus their rank in the
        requested statKey across all teams in the event. Accepts account ID (32 hex chars) or display name —
        clan tags are stripped for matching.

        ``GET /api/v1/events/stats/{eventId}/{eventWindowId}/{statKey}/{teamIdentifier}``
        """
        return self._t.request(
            "GET",
            f"/events/stats/{path_segment(event_id)}/{path_segment(event_window_id)}/{path_segment(stat_key)}/{path_segment(team_identifier)}",
            "v1",
            params={"twitter": twitter},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=TeamEventStatsDto,
            retryable=True,
        )

    def get_tokens(self, team_account_ids: list[str], *, fortnite_token: str | None = None) -> PlayerTokensDto:
        """Get the raw token set for one or more players directly from Epic's tokens endpoint. Tokens represent
        eligibility flags earned by participating in tournaments. Pass multiple IDs as comma-separated
        values: ?teamAccountIds=id1%2Cid2%2C...

        ``GET /api/v1/events/tokens``
        """
        return self._t.request(
            "GET",
            "/events/tokens",
            "v1",
            params={"teamAccountIds": ",".join(team_account_ids)},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PlayerTokensDto,
            retryable=True,
        )

    def get_tracker(
        self, *, account_id: str | None = None, valid_only: bool | None = None, fortnite_token: str | None = None
    ) -> Any:
        """Get tournament tracker data for a player — token progression and past event participation. Requires
        x-fortnite-token and accountId.

        ``GET /api/v1/events/tracker``
        """
        return self._t.request(
            "GET",
            "/events/tracker",
            "v1",
            params={"accountId": account_id, "validOnly": valid_only},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def get_tracker_eligibility(
        self,
        *,
        account_id: str | None = None,
        days: int | None = None,
        required_tournaments: int | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Check whether a player is eligible for tournaments based on their participation history. Eligibility
        is determined by the number of tournaments played in the last N days. Requires x-fortnite-token and
        accountId. Epic's live payload only remembers about a day of participation, so history older than
        that is rebuilt from per-window leaderboards in the background. The response carries a `history`
        block saying how much of the look-back has actually been verified. Until `history.complete` is true,
        `tournaments_played` is a LOWER BOUND and `eligible` is `null` rather than `false` — reaching the
        threshold still proves eligibility, but falling short proves nothing yet. The first call for a
        player kicks off that backfill; it takes a few minutes.

        ``GET /api/v1/events/tracker/eligibility``
        """
        return self._t.request(
            "GET",
            "/events/tracker/eligibility",
            "v1",
            params={"accountId": account_id, "days": days, "requiredTournaments": required_tournaments},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    def check_eligibility(
        self, identifier: str, event_id: str, *, event_window_id: str | None = None, fortnite_token: str | None = None
    ) -> EventTokenEligibilityDto:
        """Check a player's eligibility for a specific event window — the token rules (requireAllTokens,
        requireAnyTokens, requireNoneTokensCaller, …) for any player, the window's additionalRequirements
        (e.g. FNCS Solos: Power Rankings top 200,000) and the minimum Account Level. With the PLAYER'S OWN
        x-fortnite-token the Power Rankings rank is read live at any depth and the Account Level exactly;
        without it the rank comes from the PR archive and the level is a lower bound, so `verdict` may be
        "unconfirmed". Accepts display name or account ID (with or without dashes).

        ``GET /api/v1/events/tracker/eligibility/{identifier}/{eventId}``
        """
        return self._t.request(
            "GET",
            f"/events/tracker/eligibility/{path_segment(identifier)}/{path_segment(event_id)}",
            "v1",
            params={"eventWindowId": event_window_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventTokenEligibilityDto,
            retryable=True,
        )


class AsyncTournamentsResource(Resource[AsyncTransportProtocol]):
    async def get_cashprize(
        self, event_window_id: str, *, fortnite_token: str | None = None
    ) -> list[CashPrizeScoringDto]:
        """Get the payout table for a specific event window.

        ``GET /api/v1/events/cashprize/{eventWindowId}``
        """
        return await self._t.request(
            "GET",
            f"/events/cashprize/{path_segment(event_window_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[CashPrizeScoringDto],
            retryable=True,
        )

    async def get_cashprizes(self, *, fortnite_token: str | None = None) -> dict[str, list[CashPrizeScoringDto]]:
        """Get all payout tables extracted from Epic's events download. Player data is stripped — only
        reward/prize structures are returned. Response is cached for 4 hours.

        ``GET /api/v1/events/cashprizes``
        """
        return await self._t.request(
            "GET",
            "/events/cashprizes",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=dict[str, list[CashPrizeScoringDto]],
            retryable=True,
        )

    async def get_current(self, *, lang: str | None = None, fortnite_token: str | None = None) -> list[GlobalEventDto]:
        """Get currently active and upcoming tournaments, enriched with CMS metadata.

        ``GET /api/v1/events/global``
        """
        return await self._t.request(
            "GET",
            "/events/global",
            "v1",
            params={"lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[GlobalEventDto],
            retryable=True,
        )

    async def get_global_history(
        self, *, lang: str | None = None, fortnite_token: str | None = None
    ) -> list[GlobalEventDto]:
        """Get all tournaments including past ones, enriched with CMS metadata.

        ``GET /api/v1/events/global/history``
        """
        return await self._t.request(
            "GET",
            "/events/global/history",
            "v1",
            params={"lang": lang},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=list[GlobalEventDto],
            retryable=True,
        )

    async def get_leaderboard(
        self,
        *,
        event_id: str | None = None,
        event_window_id: str | None = None,
        page: int | None = None,
        leaderboard_def: str | None = None,
        account_id: str | None = None,
        cumulative_id: str | None = None,
        fortnite_token: str | None = None,
    ) -> EventLeaderboardDto:
        """Get a paginated tournament leaderboard for the given event window.

        ``GET /api/v1/events/global/leaderboard``
        """
        return await self._t.request(
            "GET",
            "/events/global/leaderboard",
            "v1",
            params={
                "eventId": event_id,
                "eventWindowId": event_window_id,
                "page": page,
                "leaderboardDef": leaderboard_def,
                "accountId": account_id,
                "cumulativeId": cumulative_id,
            },
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventLeaderboardDto,
            retryable=True,
        )

    async def get_player(
        self,
        *,
        region: str | None = None,
        platform: str | None = None,
        account_id: str | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Get the authenticated player's tournament data — token progression and event participation. Requires
        x-fortnite-token and accountId.

        ``GET /api/v1/events/player``
        """
        return await self._t.request(
            "GET",
            "/events/player",
            "v1",
            params={"region": region, "platform": platform, "accountId": account_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_player_matches(
        self,
        account_id: str,
        *,
        after: str | None = None,
        before: str | None = None,
        region: str | None = None,
        platform: str | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Get a player's RECENT tournament sessions (session IDs), grouped by event window. Sourced from
        Epic's player-scoped /download data, which Epic keeps for roughly the last 36 hours only (measured
        2026-09-01) — this is not a full history. Tournament sessions only: private custom-key matches are
        not events and never appear here. Epic only serves this data to the player it belongs to, so
        x-fortnite-token is required for any account other than the service account (403 otherwise). For a
        180-day participation history use GET /events/tracker; for a token-less lookup of one tournament use
        GET {eventId}/{eventWindowId}/player/{accountId}/matches; for the match a player is in right now use
        GET player/{accountId}/session.

        ``GET /api/v1/events/player/{accountId}/matches``
        """
        return await self._t.request(
            "GET",
            f"/events/player/{path_segment(account_id)}/matches",
            "v1",
            params={"after": after, "before": before, "region": region, "platform": platform},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_player_session(self, account_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get the match a consenting player is in right now — any mode: Battle Royale, Reload, Ranked, or a
        custom-key scrim hosted by anyone. Requires the player's OWN x-fortnite-token: the token is verified
        against the accountId before anything is forwarded (403 otherwise). That token comes from Epic's
        device-authorization flow, which authenticates as the Fortnite client rather than as your
        application; Epic Account Services developer terms do not allow routing your users through it, so it
        suits tools a player runs for themselves, not third-party apps asking other players to log in.
        Because Fortnite kills every other session of an account when the game launches, store the
        deviceAuth that POST /oauth/complete returns and re-authenticate with POST /oauth/refresh-device on
        401. When Epic publishes it, sessionId is the replay match ID — pass it to /replays/{matchId} once
        the match has ended; playlist lets you filter (e.g. scrims) before parsing, and playlistSource says
        whether that playlist is the match being played (currentIsland) or only the lobby selection
        (islandSelection). sessionId can be null while inMatch is true: the id lives in the party fields the
        client uses to advertise "my friends may join or watch me", and a match that cannot be joined or
        watched can publish them empty for its whole duration. sessionSource names the field the id came
        from, and diagnostics reports, per field, whether Epic sent it present, empty or absent — presence
        only, never a value. When every field is empty, note says so and polling harder does not change it.
        The custom match key is never returned (hasCustomKey only); teammates are listed by account id only.
        inParty is false when the player's client is offline. Cached 10 s per account — polling faster gains
        nothing — and Epic's own party state lags the real match by 1-2 min. Rate limit: 1200 requests/min
        per API key.

        ``GET /api/v1/events/player/{accountId}/session``
        """
        return await self._t.request(
            "GET",
            f"/events/player/{path_segment(account_id)}/session",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_player_window_matches(
        self,
        event_id: str,
        event_window_id: str,
        account_id: str,
        *,
        rank_hint: int | None = None,
        max_pages: int | None = None,
        fortnite_token: str | None = None,
    ) -> PlayerWindowStandingDto:
        """Get a player's matches (session IDs + per-match stats) in one event window, without any player
        token: the leaderboard is scanned page by page until the player's team is found. Pass rankHint
        (their approximate final rank) to hit the right page first — without it up to maxPages pages are
        scanned in order.

        ``GET /api/v1/events/{eventId}/{eventWindowId}/player/{accountId}/matches``
        """
        return await self._t.request(
            "GET",
            f"/events/{path_segment(event_id)}/{path_segment(event_window_id)}/player/{path_segment(account_id)}/matches",
            "v1",
            params={"rankHint": rank_hint, "maxPages": max_pages},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PlayerWindowStandingDto,
            retryable=True,
        )

    async def get_scoring(self, *, fortnite_token: str | None = None) -> Any:
        """Get the per-match scoring rules (placement/elimination reward tiers) for every event window, keyed
        by eventWindowId. Extracted from Epic's events data (scoringRuleSets + scoreLocationScoringRuleSets,
        with event-template fallback).

        ``GET /api/v1/events/scoring``
        """
        return await self._t.request(
            "GET",
            "/events/scoring",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_window_scoring(self, event_window_id: str, *, fortnite_token: str | None = None) -> Any:
        """Get the per-match scoring rules for a specific event window — the authoritative "how does this
        session score" (exists before the first game is played, and differs between a weekly cup's qualifier
        round and its final).

        ``GET /api/v1/events/scoring/{eventWindowId}``
        """
        return await self._t.request(
            "GET",
            f"/events/scoring/{path_segment(event_window_id)}",
            "v1",
            params=None,
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_sessions(self, *, event_id: str | None = None, fortnite_token: str | None = None) -> EventSessionDto:
        """Get sessions for a specific event.

        ``GET /api/v1/events/sessions``
        """
        return await self._t.request(
            "GET",
            "/events/sessions",
            "v1",
            params={"eventId": event_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventSessionDto,
            retryable=True,
        )

    async def get_stat_leaders(
        self,
        event_id: str,
        event_window_id: str,
        stat_key: str,
        *,
        top: int | None = None,
        fortnite_token: str | None = None,
    ) -> EventStatsLeaderboardDto:
        """Get the top performers for a specific tracked stat across the entire leaderboard. Fetches all pages
        in parallel batches so low-scoring but high-stat teams (e.g. top fraggers in a placement-only event)
        are always included regardless of their leaderboard position. Response includes an `availableStats`
        array listing every stat key tracked in this tournament.

        ``GET /api/v1/events/stats/{eventId}/{eventWindowId}/{statKey}``
        """
        return await self._t.request(
            "GET",
            f"/events/stats/{path_segment(event_id)}/{path_segment(event_window_id)}/{path_segment(stat_key)}",
            "v1",
            params={"top": top},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventStatsLeaderboardDto,
            retryable=True,
        )

    async def get_team_stats(
        self,
        event_id: str,
        event_window_id: str,
        stat_key: str,
        team_identifier: str,
        *,
        twitter: bool | None = None,
        fortnite_token: str | None = None,
    ) -> TeamEventStatsDto:
        """Get all tracked stats for a specific team identified by Epic account ID or display name. Returns
        every stat tracked in this tournament for that team (total + per-game), plus their rank in the
        requested statKey across all teams in the event. Accepts account ID (32 hex chars) or display name —
        clan tags are stripped for matching.

        ``GET /api/v1/events/stats/{eventId}/{eventWindowId}/{statKey}/{teamIdentifier}``
        """
        return await self._t.request(
            "GET",
            f"/events/stats/{path_segment(event_id)}/{path_segment(event_window_id)}/{path_segment(stat_key)}/{path_segment(team_identifier)}",
            "v1",
            params={"twitter": twitter},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=TeamEventStatsDto,
            retryable=True,
        )

    async def get_tokens(self, team_account_ids: list[str], *, fortnite_token: str | None = None) -> PlayerTokensDto:
        """Get the raw token set for one or more players directly from Epic's tokens endpoint. Tokens represent
        eligibility flags earned by participating in tournaments. Pass multiple IDs as comma-separated
        values: ?teamAccountIds=id1%2Cid2%2C...

        ``GET /api/v1/events/tokens``
        """
        return await self._t.request(
            "GET",
            "/events/tokens",
            "v1",
            params={"teamAccountIds": ",".join(team_account_ids)},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=PlayerTokensDto,
            retryable=True,
        )

    async def get_tracker(
        self, *, account_id: str | None = None, valid_only: bool | None = None, fortnite_token: str | None = None
    ) -> Any:
        """Get tournament tracker data for a player — token progression and past event participation. Requires
        x-fortnite-token and accountId.

        ``GET /api/v1/events/tracker``
        """
        return await self._t.request(
            "GET",
            "/events/tracker",
            "v1",
            params={"accountId": account_id, "validOnly": valid_only},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def get_tracker_eligibility(
        self,
        *,
        account_id: str | None = None,
        days: int | None = None,
        required_tournaments: int | None = None,
        fortnite_token: str | None = None,
    ) -> Any:
        """Check whether a player is eligible for tournaments based on their participation history. Eligibility
        is determined by the number of tournaments played in the last N days. Requires x-fortnite-token and
        accountId. Epic's live payload only remembers about a day of participation, so history older than
        that is rebuilt from per-window leaderboards in the background. The response carries a `history`
        block saying how much of the look-back has actually been verified. Until `history.complete` is true,
        `tournaments_played` is a LOWER BOUND and `eligible` is `null` rather than `false` — reaching the
        threshold still proves eligibility, but falling short proves nothing yet. The first call for a
        player kicks off that backfill; it takes a few minutes.

        ``GET /api/v1/events/tracker/eligibility``
        """
        return await self._t.request(
            "GET",
            "/events/tracker/eligibility",
            "v1",
            params={"accountId": account_id, "days": days, "requiredTournaments": required_tournaments},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=None,
            retryable=True,
        )

    async def check_eligibility(
        self, identifier: str, event_id: str, *, event_window_id: str | None = None, fortnite_token: str | None = None
    ) -> EventTokenEligibilityDto:
        """Check a player's eligibility for a specific event window — the token rules (requireAllTokens,
        requireAnyTokens, requireNoneTokensCaller, …) for any player, the window's additionalRequirements
        (e.g. FNCS Solos: Power Rankings top 200,000) and the minimum Account Level. With the PLAYER'S OWN
        x-fortnite-token the Power Rankings rank is read live at any depth and the Account Level exactly;
        without it the rank comes from the PR archive and the level is a lower bound, so `verdict` may be
        "unconfirmed". Accepts display name or account ID (with or without dashes).

        ``GET /api/v1/events/tracker/eligibility/{identifier}/{eventId}``
        """
        return await self._t.request(
            "GET",
            f"/events/tracker/eligibility/{path_segment(identifier)}/{path_segment(event_id)}",
            "v1",
            params={"eventWindowId": event_window_id},
            json_body=None,
            fortnite_token=fortnite_token,
            response_type=EventTokenEligibilityDto,
            retryable=True,
        )
